### ISSUE TITLE
need to dump some ideas, niggles, code snippets etc

### ISSUE THREAD

**Issue by IanESmith** [seemy-energy/vision#1]
@chrisns and not sure of the protocol, process. should I create a page to dump stuff in and you can cherry pick anything you think has value and formalise it into the readme or indeed some working code? Am playing the part of someone new to your product and thinking of all the questions id be asking, want to capture them

**Comment by chrisns** [comment]
join the [slack](https://join.slack.com/t/need-a-name-workspace/shared_invite/zt-f6s0bodx-_XDLTbZBGOMk4~TS5x7kTQ) and chat there is probably the easiest immediate direction

We need to figure out the formats and where things fit and how to organise it all for (for a first stab) so we can talk through what is in your head and find the best place to capture it :)

**Comment by IanESmith** [comment]
ta
